#!/usr/bin/env ansible-playbook
---

- hosts: all
  vars_files:
    - vars/gpdb.yml
  remote_user: root
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
    - name: 33. copy files for initialize greenplum master
      copy:
        src: '{{ item }}'
        dest: '/home/{{ greenplum_admin_user }}/'
        remote_src: no
      with_items:
        - gpnodes/gpadmin_hosts
        - template/gpadmin_auto_ssh.sh
        - template/initdb_gpdb.sql
    - name: 34. replace greenplum admin user environment bash file
      template: src=template/gpadmin_bashrc.j2 dest=/home/{{ greenplum_admin_user }}/.bashrc
    - name: 35. calculate greenplum primary segment instance
      shell: |
        primary_path_all=""; \
        for i in `seq 1 {{ greenplum_primay_segments_per_host_number }}` ; do \
            primary_path_all="$primary_path_all {{ greenplum_data_directory }}/primary"; \
        done; \
        echo $primary_path_all
      register: primary_path_all
    - name: 36. calculate greenplum mirror segment instance
      shell: |
        mirror_path_all=""; \
        for i in `seq 1 {{ greenplum_primay_segments_per_host_number }}` ; do \
            mirror_path_all="$mirror_path_all {{ greenplum_data_directory }}/mirror"; \
        done; \
        echo $mirror_path_all 
      register: mirror_path_all
    - name: 37. copy and configure gpinitsystem config file
      template: src=template/gpinitsystem_config.j2 dest=/home/{{ greenplum_admin_user }}/gpinitsystem_config
    - name: 38. change data directory ownership
      file:
        path: '/home/{{ greenplum_admin_user }}/'
        owner: '{{ greenplum_admin_user }}'
        group: '{{ greenplum_admin_user }}'
        recurse: yes
    - name: 39. configure greenplum admin user auto login
      shell: sh /home/{{ greenplum_admin_user }}/gpadmin_auto_ssh.sh /home/{{ greenplum_admin_user }}/gpadmin_hosts
      become: yes
      become_user: '{{ greenplum_admin_user }}'
    - name: 40. initialize greenplum master database
      shell: "gpinitsystem -a --ignore-warnings -c /home/{{ greenplum_admin_user }}/gpinitsystem_config -h /home/{{ greenplum_admin_user }}/segment_hosts -s {{ greenplum_standby_node_hostname }}"
      become: yes
      become_method: su
      become_flags: '-'
      become_user: '{{ greenplum_admin_user }}'
    - name: 41. configure greenplum database
      shell: '{{ item }}'
      become: yes
      become_method: su
      become_flags: '-'
      become_user: '{{ greenplum_admin_user }}'
      with_items:
        - "psql -d postgres -U gpadmin -f /home/{{ greenplum_admin_user }}/initdb_gpdb.sql"
        - "echo \"host  all  all  0.0.0.0/0  password\" >> {{ greenplum_data_directory }}/master/gpseg-1/pg_hba.conf"
        - "gpconfig -c log_statement -v none"
        - "gpconfig -c gp_enable_global_deadlock_detector -v on"
        - "sleep 5 && gpstop -u"